-- customer.customers definition

-- Drop table

-- DROP TABLE customer.customers;

CREATE TABLE customer.customers (
	registration_date date NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	tckn varchar(11) NOT NULL,
	first_name varchar(255) NOT NULL,
	last_name varchar(255) NOT NULL,
	CONSTRAINT customers_pkey PRIMARY KEY (id),
	CONSTRAINT customers_tckn_key UNIQUE (tckn),
	CONSTRAINT customers_user_id_key UNIQUE (user_id)
);

-- Permissions

ALTER TABLE customer.customers OWNER TO postgres;
GRANT ALL ON TABLE customer.customers TO postgres;


-- customer.customers foreign keys

ALTER TABLE customer.customers ADD CONSTRAINT fkrh1g1a20omjmn6kurd35o3eit FOREIGN KEY (user_id) REFERENCES customer.users(userid);