-- customer.users definition

-- Drop table

-- DROP TABLE customer.users;

CREATE TABLE customer.users (
	userid int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"password" varchar(255) NOT NULL,
	username varchar(255) NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (userid),
	CONSTRAINT users_username_key UNIQUE (username)
);

-- Permissions

ALTER TABLE customer.users OWNER TO postgres;
GRANT ALL ON TABLE customer.users TO postgres;